# Generated by Django 3.1.5 on 2021-01-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='filemod',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='fileS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.filemod'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='userS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
