# Generated by Django 3.1.5 on 2021-01-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210109_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemod',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
    ]
