# Generated by Django 3.1.5 on 2021-01-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210113_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fileS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.filemod'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='userS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
