# Generated by Django 3.1.5 on 2021-01-16 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210116_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='userS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
