# Generated by Django 3.1.5 on 2021-01-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210109_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', django_enumfield.db.fields.EnumField(default=5, enum=myapp.models.Rate)),
                ('fileS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.filemod')),
                ('userS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
