# Generated by Django 3.1.5 on 2021-01-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210113_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fileS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.filemod'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='userS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
    ]
