# Generated by Django 3.1.5 on 2021-01-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='fileS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.filemod'),
        ),
    ]
