# Generated by Django 3.1.5 on 2021-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210116_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemod',
            name='f_rate',
            field=models.ImageField(default=0, upload_to='', verbose_name='file_rate'),
        ),
    ]
