# Generated by Django 3.1.5 on 2021-01-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_filemod_f_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='id',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='fileS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.filemod'),
        ),
    ]
